name: Build and Package cf_ddns

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: x86_64
            target: x86_64-linux-gnu
            image: dockcross/linux-x64
            ext: ""
          - os: linux
            arch: x86
            target: i686-linux-gnu
            image: dockcross/linux-x86
            ext: ""
          - os: linux
            arch: armv7
            target: armv7-linux-gnueabihf
            image: dockcross/linux-armv7
            ext: ""
          - os: linux
            arch: aarch64
            target: aarch64-linux-gnu
            image: dockcross/linux-arm64
            ext: ""
          - os: windows
            arch: x86_64
            target: x86_64-w64-mingw32
            image: dockcross/windows-static-x64
            ext: ".exe"
          - os: windows
            arch: x86
            target: i686-w64-mingw32
            image: dockcross/windows-static-x86
            ext: ".exe"

    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull dockcross image and create script
        run: |
          docker run --rm ${{ matrix.image }} > ./dockcross
          chmod +x ./dockcross

      - name: Download json.hpp if missing
        run: |
          [ -f json.hpp ] || curl -L -o json.hpp https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp

      - name: Build binary
        run: |
          ./dockcross bash -c "make CXX=\$CXX EXT=${{ matrix.ext }}"

      - name: Build binary
        run: |
          ./dockcross bash -c "make CXX=\$CXX EXT=${{ matrix.ext }}"

      - name: Prepare package
        run: |
          mkdir -p out
          cp cf_ddns${{ matrix.ext }} out/cf_ddns-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
          cp config.json out/
          cd out && zip cf_ddns-${{ matrix.os }}-${{ matrix.arch }}.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cf_ddns-${{ matrix.os }}-${{ matrix.arch }}
          path: out/cf_ddns-${{ matrix.os }}-${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/cf_ddns-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
