name: Build and Package cf_ddns

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linux x86_64：使用 linux-x86_64-full（预装静态 libcurl/openssl）
          - os: linux
            arch: x86_64
            image: dockcross/linux-x86_64-full
            ext: ""
          # Linux x86：切换到 linux-x86-full（预装静态 libcurl/openssl）
          - os: linux
            arch: x86
            image: dockcross/linux-x86-full
            ext: ""
          # Linux ARMv7：如果有 linux-armv7-full，请替换；否则保持原镜像并手动安装
          - os: linux
            arch: armv7
            image: dockcross/linux-armv7-full
            ext: ""
          # Linux aarch64：使用 linux-arm64-full（预装静态 libcurl/openssl）
          - os: linux
            arch: aarch64
            image: dockcross/linux-arm64-full
            ext: ""
          # Windows x86_64：自带静态 libcurl/openssl
          - os: windows
            arch: x86_64
            image: dockcross/windows-static-x64
            ext: ".exe"
          # Windows x86：自带静态 libcurl/openssl
          - os: windows
            arch: x86
            image: dockcross/windows-static-x86
            ext: ".exe"

    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate dockcross script
        run: |
          docker run --rm ${{ matrix.image }} > ./dockcross
          chmod +x ./dockcross

      - name: Download json.hpp if missing
        run: |
          [ -f json.hpp ] || curl -L -o json.hpp https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp

      # 只有 armv7 平台还需要手动安装静态库
      - name: Install static dependencies (armv7 only)
        if: matrix.arch == 'armv7'
        run: |
          ./dockcross bash -c "\
            apt-get update && \
            apt-get install -y libcurl4-openssl-dev libssl-dev zlib1g-dev"

      - name: Build binary
        run: |
          ./dockcross bash -c "set -x; make CXX=\$CXX EXT=${{ matrix.ext }}"

      - name: Prepare package
        run: |
          mkdir -p out
          cp cf_ddns${{ matrix.ext }} out/cf_ddns-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
          cp config.json out/
          cd out && zip cf_ddns-${{ matrix.os }}-${{ matrix.arch }}.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cf_ddns-${{ matrix.os }}-${{ matrix.arch }}
          path: out/cf_ddns-${{ matrix.os }}-${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/cf_ddns-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
